/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-opencv-qr.h
 #	source generated by 4D Plugin Wizard
 #	Project : opencv-qr
 #	author : miyako
 #	2022/06/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_OPENCV_QR_H
#define PLUGIN_OPENCV_QR_H

// Must be defined before ANYTHING that might pull in <windows.h> (this
// header itself, 4DPluginAPI.h, OpenCV's Windows core headers, and
// gdiplus.h all can). Without it, whichever of those happens to include
// <windows.h> first also drags in the legacy <winsock.h>; when
// 4DPlugin-JSON.h later includes <winsock2.h>/<ws2tcpip.h> (its own
// "winsock2 before windows" ordering only protects against headers
// included after it, not before), the two winsock generations collide -
// sockaddr/fd_set redefinitions and a cascade of ws2tcpip.h errors.
// WIN32_LEAN_AND_MEAN stops windows.h from auto-including winsock.h at
// all, so the collision can't happen regardless of include order.
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include "4DPluginAPI.h"

#if VERSIONMAC
#include "TargetConditionals.h"
#if TARGET_CPU_ARM64
#include "arm/opencv4/opencv2/core.hpp"
#include "arm/opencv4/opencv2/imgcodecs.hpp"
#include "arm/opencv4/opencv2/imgcodecs/macosx.h"
#include "arm/opencv4/opencv2/objdetect.hpp"
#else
#include "intel/opencv4/opencv2/core.hpp"
#include "arm/opencv4/opencv2/imgcodecs.hpp"
#include "intel/opencv4/opencv2/imgcodecs/macosx.h"
#include "intel/opencv4/opencv2/objdetect.hpp"
#endif
#else
#include "opencv2/core.hpp"
#include "opencv2/imgcodecs.hpp"
#include "opencv2/objdetect.hpp"
#ifndef max
#define max(a,b) (((a) > (b)) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) (((a) < (b)) ? (a) : (b))
#endif
#endif


#if VERSIONMAC
#import <Accelerate/Accelerate.h>
#import <AVFoundation/AVFoundation.h>
#import <ImageIO/ImageIO.h>
#else
#include <shlwapi.h>
#include <gdiplus.h>
#endif

#include "4DPlugin-JSON.h"

#include "C_TEXT.h"

#pragma mark -

void opencv_decode_qrcode(PA_PluginParameters params, PA_long32 selector);

#endif /* PLUGIN_OPENCV_QR_H */
