/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-opencv-qr.h
 #	source generated by 4D Plugin Wizard
 #	Project : opencv-qr
 #	author : miyako
 #	2022/06/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_OPENCV_QR_H
#define PLUGIN_OPENCV_QR_H

#include "4DPluginAPI.h"

#if VERSIONMAC
#include "TargetConditionals.h"
#if TARGET_CPU_ARM64
#include "arm/opencv4/opencv2/core.hpp"
#include "arm/opencv4/opencv2/imgcodecs.hpp"
#include "arm/opencv4/opencv2/imgcodecs/macosx.h"
#include "arm/opencv4/opencv2/objdetect.hpp"
#else
#include "intel/opencv4/opencv2/core.hpp"
#include "arm/opencv4/opencv2/imgcodecs.hpp"
#include "intel/opencv4/opencv2/imgcodecs/macosx.h"
#include "intel/opencv4/opencv2/objdetect.hpp"
#endif
#else
#include "opencv2/core.hpp"
#include "opencv2/imgcodecs.hpp"
#include "opencv2/objdetect.hpp"
#ifndef max
#define max(a,b) (((a) > (b)) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) (((a) < (b)) ? (a) : (b))
#endif
#endif


#if VERSIONMAC
#import <Accelerate/Accelerate.h>
#import <AVFoundation/AVFoundation.h>
#import <ImageIO/ImageIO.h>
#else
#include <shlwapi.h>
#include <gdiplus.h>
#endif

#include "4DPlugin-JSON.h"

#include "C_TEXT.h"

#pragma mark -

void opencv_decode_qrcode(PA_PluginParameters params);

#endif /* PLUGIN_OPENCV_QR_H */
